server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /items/ {
        proxy_pass https://taskapp-backend247-cmcvfxcebsg9gbdy.ukwest-01.azurewebsites.net;
        proxy_ssl_server_name on;
        proxy_set_header Host taskapp-backend247-cmcvfxcebsg9gbdy.ukwest-01.azurewebsites.net;
        proxy_set_header Authorization $http_authorization;
    }

    location /users/ {
        proxy_pass https://taskapp-backend247-cmcvfxcebsg9gbdy.ukwest-01.azurewebsites.net;
        proxy_ssl_server_name on;
        proxy_set_header Host taskapp-backend247-cmcvfxcebsg9gbdy.ukwest-01.azurewebsites.net;
        proxy_set_header Authorization $http_authorization;
    }

    location /login {
        proxy_pass https://taskapp-backend247-cmcvfxcebsg9gbdy.ukwest-01.azurewebsites.net;
        proxy_ssl_server_name on;
        proxy_set_header Host taskapp-backend247-cmcvfxcebsg9gbdy.ukwest-01.azurewebsites.net;
    }

    location /files/ {
        proxy_pass https://taskapp-backend247-cmcvfxcebsg9gbdy.ukwest-01.azurewebsites.net;
        proxy_ssl_server_name on;
        proxy_set_header Host taskapp-backend247-cmcvfxcebsg9gbdy.ukwest-01.azurewebsites.net;
        proxy_set_header Authorization $http_authorization;
    }

    location /docs {
        proxy_pass https://taskapp-backend247-cmcvfxcebsg9gbdy.ukwest-01.azurewebsites.net;
        proxy_ssl_server_name on;
        proxy_set_header Host taskapp-backend247-cmcvfxcebsg9gbdy.ukwest-01.azurewebsites.net;
    }

    location /redoc {
        proxy_pass https://taskapp-backend247-cmcvfxcebsg9gbdy.ukwest-01.azurewebsites.net;
        proxy_ssl_server_name on;
        proxy_set_header Host taskapp-backend247-cmcvfxcebsg9gbdy.ukwest-01.azurewebsites.net;
    }

    location = /openapi.json {
        proxy_pass https://taskapp-backend247-cmcvfxcebsg9gbdy.ukwest-01.azurewebsites.net;
        proxy_ssl_server_name on;
        proxy_set_header Host taskapp-backend247-cmcvfxcebsg9gbdy.ukwest-01.azurewebsites.net;
    }
}
